### ISSUE TITLE
`useOptimisticAction` overwrites optimistic state with previous state

### ISSUE THREAD

**Issue by tmns** [TheEdoRan/next-safe-action#10]
It seems that `useOptimisticAction` is prematurely overwriting the "optimistic state", i.e. the state passed in as the second arg to the returned `execute` function, once the corresponding API request has resolved. This results in an "old state -> updated (optimistic) state -> old state -> updated state" behavior:

<details>
<summary>Ex.</summary>
<video src="https://github.com/TheEdoRan/next-safe-action/assets/35785003/73ce2208-d2c0-4c5f-ab32-7dae13ca543a" />
</details>

Note in the example above, the optimistic state gets set correctly upon click, but then once the request resolves the state reverts back to the original state, and finally upon refresh of the route (via the action running `revalidatePath('<path>')`), the updated state comes back in via props.

I believe this may be due to the `res` state [here](https://github.com/TheEdoRan/next-safe-action/blob/main/src/hook.ts#L148) being updated, which causes a rerender & in turn for the hook to be reran, [setting `optState` back to `deaultOptState`](https://github.com/TheEdoRan/next-safe-action/blob/main/src/hook.ts#L131), which of course is still the (old) state we originally rendered the component with. Locally, if I spread `res.data` into the default state as well, it works as expected, since the updated state gets set as the optimistic state. You can see me doing that [here](https://github.com/tmns/lists-next-13-app/blob/main/src/lib/next-safe-action-hooks.ts#L68-L75).

Is that the issue or am I just actually using the hook incorrectly? 🤔 

You can see exactly how I'm using it [here](https://github.com/tmns/lists-next-13-app/blob/main/src/lib/next-safe-action-hooks.ts#L68-L75), which is where the example noted above also comes from.

**Comment by TheEdoRan** [comment]
Thank you very much for opening this pretty interesting issue!

After doing some tests using "Slow 3G" throttling mode in Chrome dev tools and looking at requests, I realized that the mismatch is visible when Next is revalidating stylesheet (layout.css). Therefore, I'm not sure if this is a library problem or a Next.js one.

Your solution seems to work fine if `optimisticState` type is the same as action output (`AO`). If it's different, though, the issue persists, because spreading `res.data` makes no difference when the user expects a different object returned by the hook.

So, I think I'll need to force the same type (or partial type) as output (`res.data`) for the optimistic state, at least as a temporary solution, but it would probably make sense to keep it this way in the future too, from a user's perspective, I guess.
I'll work on the fix later today, expect a merged PR soon.

**Comment by tmns** [comment]
Nice! Thanks for the quick fix; I tested it out on my end and it works.

That's a good point though about the response data not necessarily being the same type as the optimistic state. I could see that being a frustrating limitation for some folks. But at any rate, as you said this could serve as a decent temporary solution. The underlying hook itself is experimental anyway, so I expect it'll still change quite a bit. Curious as to whether this could be solved on Next's end as well.
