### ISSUE TITLE
[BUG] Errors with example from docs

### ISSUE THREAD

**Issue by nikitavoloboev** [TheEdoRan/next-safe-action#112]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

<img width="862" alt="image" src="https://github.com/TheEdoRan/next-safe-action/assets/6391776/b37f3796-cef3-475e-aa5d-e4ac9851aa73">

in code of my project: https://github.com/kuskusapp/kuskus/blob/main/app/update-user-action.ts

not sure what's wrong

also I want to use server action here:

<img width="463" alt="image" src="https://github.com/TheEdoRan/next-safe-action/assets/6391776/31522d3e-7f84-4ee5-a86e-342d8e88919d">

https://github.com/kuskusapp/kuskus/blob/main/components/routes/ProfileAuth.tsx#L52

can I inline server action somewhere inside the `ProfileAuth` route itself?

thanks

### Reproduction steps

clone repo, check the types in the `update-user-action.ts` file

### Expected behavior

no type errors

### Reproduction example

https://github.com/kuskusapp/kuskus

### Operating System

macOS

### Library version

^6.2.0

**Comment by TheEdoRan** [comment]
You need to install the library with `npm i next-safe-action@next` if you want to use the v7 API. The problem is that you're using current stable version (v6). You can check out documentation for v6 [here](https://next-safe-action.dev) and for upcoming v7 [here](https://next.next-safe-action.dev). Please note that v7 is currently in beta and APIs could change, thanks.
