### ISSUE TITLE
[BUG] optimisticState not updated immediately

### ISSUE THREAD

**Issue by matthiasbayer** [TheEdoRan/next-safe-action#251]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

The `optimisticState` prop exposed by the `useOptimisticAction` hook is not updated immediately after calling `execute`.

### Reproduction steps

See code
- Consume an action using the `useOptimisticAction` hook
- Call `.execute` 
- Immediately access the `optimisticState` property
- Observe that the value of the property was not updated optimistically

### Expected behavior

`optimisticState` should reflect the updated value immediately after `execute` was called, as stated in the docs.

### Minimal reproduction example

https://codesandbox.io/p/sandbox/priceless-mclean-nz7ywx

### Operating System

macOS

### Library version

7.7.0

### Next.js version

14.2.7

### Node.js version

20.16.0

**Comment by matthiasbayer** [comment]
Will post a CodeSandbox tomorrow so it's easier to reproduce!

**Comment by matthiasbayer** [comment]
Added a CodeSandbox link with a minimal reproduction repo

https://codesandbox.io/p/sandbox/priceless-mclean-nz7ywx

Click the "mutate!" button and check the console output

**Comment by TheEdoRan** [comment]
Hi, I wouldn't say this is a bug, this is how React works, the same happens when setting the state and trying to access the new value immediately after. React has to re-render the component in order to update the state:

```tsx
export default function TestPage() {
  const [state, setState] = useState("foo");

  useEffect(() => {
    setState("bar");
    console.log(state);
  }, [state]);

  return null;
}
```

This will print:
```
hey
hey
yo
```

to browser console ("hey" gets printed twice due to React strict mode).

The `execute` function works in the same way, since the `useOptimisticAction` hook uses React's `useOptimistic` hook under the hood.

**Comment by matthiasbayer** [comment]
Hey! Thanks for looking into this. I think this is a documentation issue:

`optimisticState`: the optimistic state updated immediately after the action is executed, with the behavior defined in updateFn

from https://next-safe-action.dev/docs/execute-actions/hooks/useoptimisticaction#useoptimisticaction-return-object

Reading this, the emphasize on _immediately_ sounds to me like this value would be not tied to a state update, but can rather be accessed right after executing the action. This is a bit misleading imho. Maybe the wording needs an update or clarification.

**Comment by TheEdoRan** [comment]
> Reading this, the emphasize on _immediately_ sounds to me like this value would be not tied to a state update, but can rather be accessed right after executing the action. This is a bit misleading imho. Maybe the wording needs an update or clarification.

Thanks for your feedback. I'll see if I can come up with better wording. "Immediately", in that sentence, means that the `optimisticState` gets updated right after you call `execute` (next component render), it doesn't wait for the action to complete its execution to do it. So, it's like a regular `setState`, and the behavior of the state update is defined by the user inside the `updateFn` passed to the hook. The API is very similar to the under the hood React [`useOptimistic`](https://react.dev/reference/react/useOptimistic) hook, since it's just a type safe wrapper around it, with some additional options, such as callbacks.

Hope this helps, let me know if I can help you with something else. Keeping this issue open until I update that documentation section.

**Comment by TheEdoRan** [comment]
Updated [`useOptimisticAction`](https://next-safe-action.dev/docs/execute-actions/hooks/useoptimisticaction) page on the website.
