### ISSUE TITLE
[DOCS] Add React Hook Form integration

### ISSUE THREAD

**Issue by TheEdoRan** [TheEdoRan/next-safe-action#63]
Explain how to integrate next-safe-action with React Hook Form.

**Comment by rwieruch** [comment]
@TheEdoRan is there any timeline for the v7 release? Would love to show off this library on my blog, but hopefully without breaking changes. 

Related question to this issue: I saw this https://github.com/TheEdoRan/next-safe-action/issues/29 Will this be supported without React Hook Form too? I like React Hook Form, but I would find it better if it were just opt-in, so that more form libraries would have the opportunity in the future to work with your library.

**Comment by TheEdoRan** [comment]
Hi @rwieruch, so, I think React Hook Form + next-safe-action combo is great in terms of DX, but version 7 of the library will actually support Form Actions, so the new major release will be rolled out when those are implemented.

The development for v7 is in the [`next` branch](https://github.com/TheEdoRan/next-safe-action/tree/next), and you can actually already install the new version with:

```sh
npm i next-safe-action@next
```

You can also explore the documentation for the upcoming version [here](https://next.next-safe-action.dev/), still WIP.

Unfortunately, I can't give you an exact release date at the moment, but I believe I am now on the right track regarding the implementation of Form Actions, so it's just a matter of time. Hope this helps!

**Comment by nealchandra** [comment]
@TheEdoRan form actions are currently referenced in the v6 docs I thought, is the approach in v7 expanding further on that? I can't see anything in the v7 docs that looks different and would love to learn more about what you're working on.

Would you expect integration with React Hook Form to work in v6? I'm running into some mysterious issues trying to call `execute` in `form.handleSubmit` and wondering if these are expected to play nicely with each other currently.
