### ISSUE TITLE
[FEATURE] Return async function from hooks

### ISSUE THREAD

**Issue by pharmarin** [TheEdoRan/next-safe-action#72]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Suggest an idea

I would like to have an async function returned from hooks. This function would be executed from event handlers to set internal state with more granularity.

**Comment by TheEdoRan** [comment]
Hi @pharmarin, I don't think this is possible, since next-safe-action hooks use the `startTransition` hook from React under the hood. If you need to call Server Actions from event handlers, I suggest to directly import them inside your Client Components.

Please let me know if this solves your issue, thanks.

**Comment by pharmarin** [comment]
I really need to await and catch the call while getting current status in my component. So I "created" a hook that does the work

**Comment by TheEdoRan** [comment]
Unfortunately this isn't currently supported, and it isn't a next-safe-action issue, so there's not much I can do to fix it. Please track [this issue](https://github.com/facebook/react/issues/25642) from React to get updates regarding this. At this time, though, [React documentation](https://react.dev/reference/react/useTransition) states: 

> The function you pass to startTransition must be synchronous. React immediately executes this function, marking all state updates that happen while it executes as transitions. If you try to perform more state updates later (for example, in a timeout), they won’t be marked as transitions.

React recommends to use `useTransition` hook to handle mutations on the client, but if you don't need to use it in your specific case, creating a custom hook as you did is acceptable, I think. Hope this helps.

**Comment by pharmarin** [comment]
This will be perfect when it gets merged : https://github.com/facebook/react/pull/28491

**Comment by TheEdoRan** [comment]
Yes @pharmarin! That hook will surely change the way we handle Server Actions in next-safe-action, and also pave the way for Form Actions support. [Here are my thoughts](https://github.com/TheEdoRan/next-safe-action/issues/29#issuecomment-1983317144), related to this issue as well.

**Comment by TheEdoRan** [comment]
I'm implementing stateful actions in the library right now, since the new hook is finally available in Next.js, and I just found out that `useActionState` doesn't return an async dispatcher, it returns instead a function with the signature: `() => void`, so apparently it's not going to solve this issue.
